version: '3.8'

services:
  backend:
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    restart: unless-stopped
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Security: run as non-root user
    user: "1000:1000"
    # Health check with longer intervals for production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 60s

  frontend:
    restart: unless-stopped
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    # Health check with longer intervals for production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s

# Production volumes with better persistence
volumes:
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/cosinorlab/data

# Production network with better isolation
networks:
  cosinorlab-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cosinorlab-br0 