services:
  # Backend Service
  - type: web
    name: cosinorlab-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install cosinorage-0.1.4.tar.gz
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: cosinorlab-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://cosinorlab-backend.onrender.com
    autoDeploy: true 